version: '3.5'

services:
  web:
    build:
      context: .
    container_name: qm_web
    command: gunicorn --workers=3 --bind 0.0.0.0:8000 qmeter.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - web
   

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - web
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      retries: 3
      timeout: 10s

networks:
  web:
    driver: bridge

volumes:
  mongo_data:
